apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-heroes
  labels:
    app: api-heroes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-heroes
  template:
    metadata:
      labels:
        app: api-heroes
    spec:
      containers:
      - name: api-heroes
        image: hyd.ocir.io/axwepzpfvpxt/demorepo/heroes:latest
        env:
          - name: PORT
            value: "3333"
          - name: POSTGRES_DB
            value: heroes
          - name: POSTGRES_HOST
            value: postgres:welcome1@10.4.1.45:5432
        ports:
        - containerPort: 3333
      imagePullSecrets:
        - name: ocirsecret
