apiVersion: v1
kind: Service
metadata:
  name: api-heroes-svc
  labels:
    app: api-heroes
    version: v1
spec:
  selector:
    app: api-heroes
  type: LoadBalancer
  ports:
  - port: 3333
    protocol: TCP
    targetPort: 3333